// <auto-generated />
using System;
using DobuMartial_project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DobuMartial_project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427145218_juniormembershipjunioriskidsnowoops")]
    partial class juniormembershipjunioriskidsnowoops
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DobuMartial_project.Models.Class", b =>
                {
                    b.Property<int>("ClassID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassID"));

                    b.Property<bool>("IsKids")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClassID");

                    b.HasIndex("UserId");

                    b.ToTable("Class");

                    b.HasData(
                        new
                        {
                            ClassID = 1,
                            IsKids = false,
                            IsPrivate = false,
                            Name = "Jiu-Jitsu"
                        },
                        new
                        {
                            ClassID = 2,
                            IsKids = false,
                            IsPrivate = false,
                            Name = "Muay-Thai"
                        },
                        new
                        {
                            ClassID = 3,
                            IsKids = false,
                            IsPrivate = true,
                            Name = "Private Tuition"
                        },
                        new
                        {
                            ClassID = 4,
                            IsKids = false,
                            IsPrivate = false,
                            Name = "Open Mat/ Personal Practise"
                        },
                        new
                        {
                            ClassID = 5,
                            IsKids = true,
                            IsPrivate = false,
                            Name = "Kids Jiu-Jitsu"
                        },
                        new
                        {
                            ClassID = 6,
                            IsKids = false,
                            IsPrivate = false,
                            Name = "Karate"
                        },
                        new
                        {
                            ClassID = 7,
                            IsKids = false,
                            IsPrivate = false,
                            Name = "Judo"
                        },
                        new
                        {
                            ClassID = 8,
                            IsKids = true,
                            IsPrivate = false,
                            Name = "Kids Judo"
                        },
                        new
                        {
                            ClassID = 9,
                            IsKids = true,
                            IsPrivate = false,
                            Name = "Kids Jiu-jitsu"
                        },
                        new
                        {
                            ClassID = 10,
                            IsKids = true,
                            IsPrivate = false,
                            Name = "Kids karate"
                        },
                        new
                        {
                            ClassID = 11,
                            IsKids = false,
                            IsPrivate = false,
                            Name = ""
                        });
                });

            modelBuilder.Entity("DobuMartial_project.Models.Day", b =>
                {
                    b.Property<int>("DayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DayID");

                    b.ToTable("WeekDays");

                    b.HasData(
                        new
                        {
                            DayID = 1,
                            Name = "Monday"
                        },
                        new
                        {
                            DayID = 2,
                            Name = "Tuesday"
                        },
                        new
                        {
                            DayID = 3,
                            Name = "Wednesday"
                        },
                        new
                        {
                            DayID = 4,
                            Name = "Thursday"
                        },
                        new
                        {
                            DayID = 5,
                            Name = "Friday"
                        },
                        new
                        {
                            DayID = 6,
                            Name = "Saturday"
                        },
                        new
                        {
                            DayID = 7,
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("DobuMartial_project.Models.Instructor", b =>
                {
                    b.Property<int>("InstructorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorID");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            InstructorID = 1,
                            Description = "Gym Owner\nHead Martial arts coach",
                            Image = "assets/img/mauricio.jpg",
                            Name = "Mauricio Gomez"
                        },
                        new
                        {
                            InstructorID = 2,
                            Description = "Assistant Martial Arts Coach",
                            Image = "assets/img/sarah.jpg",
                            Name = "Sarah Nova"
                        },
                        new
                        {
                            InstructorID = 3,
                            Description = "Assistant Martial Arts Coach",
                            Image = "assets/img/guy.jpg",
                            Name = "Guy Victory"
                        },
                        new
                        {
                            InstructorID = 4,
                            Description = "Assistant Martial Arts Coach",
                            Image = "assets/img/morris.jpg",
                            Name = "Morris Davis"
                        },
                        new
                        {
                            InstructorID = 5,
                            Description = "Fitness Coach",
                            Image = "assets/img/traci.jpg",
                            Name = "Traci Santiago"
                        },
                        new
                        {
                            InstructorID = 6,
                            Description = "Fitness Coach",
                            Image = "assets/img/harpeet.jpg",
                            Name = "Harpeet Kaur"
                        });
                });

            modelBuilder.Entity("DobuMartial_project.Models.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipId"));

                    b.Property<bool>("IsKids")
                        .HasColumnType("bit");

                    b.Property<int>("MartialArts")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sessions")
                        .HasColumnType("int");

                    b.HasKey("MembershipId");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            MembershipId = 1,
                            IsKids = false,
                            MartialArts = 1,
                            Name = "Basic",
                            Price = 25.0,
                            Sessions = 2
                        },
                        new
                        {
                            MembershipId = 2,
                            IsKids = false,
                            MartialArts = 1,
                            Name = "Intermediate",
                            Price = 35.0,
                            Sessions = 3
                        },
                        new
                        {
                            MembershipId = 3,
                            IsKids = false,
                            MartialArts = 2,
                            Name = "Advanced",
                            Price = 45.0,
                            Sessions = 5
                        },
                        new
                        {
                            MembershipId = 4,
                            IsKids = false,
                            MartialArts = 100,
                            Name = "Elite",
                            Price = 60.0,
                            Sessions = 100
                        },
                        new
                        {
                            MembershipId = 5,
                            IsKids = true,
                            MartialArts = 100,
                            Name = "Junior Membership",
                            Price = 25.0,
                            Sessions = 100
                        });
                });

            modelBuilder.Entity("DobuMartial_project.Models.Session", b =>
                {
                    b.Property<int>("SessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SessionId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("DayID")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("TimeStart")
                        .HasColumnType("time");

                    b.HasKey("SessionId");

                    b.HasIndex("ClassId");

                    b.HasIndex("DayID");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            SessionId = 1,
                            ClassId = 1,
                            DayID = 1,
                            TimeEnd = new TimeOnly(7, 30, 0),
                            TimeStart = new TimeOnly(6, 30, 0)
                        },
                        new
                        {
                            SessionId = 2,
                            ClassId = 2,
                            DayID = 1,
                            TimeEnd = new TimeOnly(10, 0, 0),
                            TimeStart = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            SessionId = 3,
                            ClassId = 3,
                            DayID = 1,
                            TimeEnd = new TimeOnly(12, 0, 0),
                            TimeStart = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            SessionId = 4,
                            ClassId = 4,
                            DayID = 1,
                            TimeEnd = new TimeOnly(14, 30, 0),
                            TimeStart = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            SessionId = 5,
                            ClassId = 5,
                            DayID = 1,
                            TimeEnd = new TimeOnly(17, 0, 0),
                            TimeStart = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            SessionId = 6,
                            ClassId = 6,
                            DayID = 1,
                            TimeEnd = new TimeOnly(19, 0, 0),
                            TimeStart = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            SessionId = 7,
                            ClassId = 7,
                            DayID = 1,
                            TimeEnd = new TimeOnly(21, 0, 0),
                            TimeStart = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            SessionId = 8,
                            ClassId = 6,
                            DayID = 2,
                            TimeEnd = new TimeOnly(7, 30, 0),
                            TimeStart = new TimeOnly(6, 30, 0)
                        },
                        new
                        {
                            SessionId = 9,
                            ClassId = 3,
                            DayID = 2,
                            TimeEnd = new TimeOnly(10, 0, 0),
                            TimeStart = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            SessionId = 10,
                            ClassId = 3,
                            DayID = 2,
                            TimeEnd = new TimeOnly(12, 0, 0),
                            TimeStart = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            SessionId = 11,
                            ClassId = 4,
                            DayID = 2,
                            TimeEnd = new TimeOnly(14, 30, 0),
                            TimeStart = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            SessionId = 12,
                            ClassId = 8,
                            DayID = 2,
                            TimeEnd = new TimeOnly(17, 0, 0),
                            TimeStart = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            SessionId = 13,
                            ClassId = 2,
                            DayID = 2,
                            TimeEnd = new TimeOnly(19, 0, 0),
                            TimeStart = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            SessionId = 14,
                            ClassId = 7,
                            DayID = 2,
                            TimeEnd = new TimeOnly(21, 0, 0),
                            TimeStart = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            SessionId = 15,
                            ClassId = 7,
                            DayID = 3,
                            TimeEnd = new TimeOnly(7, 30, 0),
                            TimeStart = new TimeOnly(6, 30, 0)
                        },
                        new
                        {
                            SessionId = 16,
                            ClassId = 3,
                            DayID = 3,
                            TimeEnd = new TimeOnly(10, 0, 0),
                            TimeStart = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            SessionId = 17,
                            ClassId = 3,
                            DayID = 3,
                            TimeEnd = new TimeOnly(12, 0, 0),
                            TimeStart = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            SessionId = 18,
                            ClassId = 4,
                            DayID = 3,
                            TimeEnd = new TimeOnly(14, 30, 0),
                            TimeStart = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            SessionId = 19,
                            ClassId = 10,
                            DayID = 3,
                            TimeEnd = new TimeOnly(17, 0, 0),
                            TimeStart = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            SessionId = 20,
                            ClassId = 7,
                            DayID = 3,
                            TimeEnd = new TimeOnly(19, 0, 0),
                            TimeStart = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            SessionId = 21,
                            ClassId = 1,
                            DayID = 3,
                            TimeEnd = new TimeOnly(21, 0, 0),
                            TimeStart = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            SessionId = 22,
                            ClassId = 1,
                            DayID = 4,
                            TimeEnd = new TimeOnly(7, 30, 0),
                            TimeStart = new TimeOnly(6, 30, 0)
                        },
                        new
                        {
                            SessionId = 23,
                            ClassId = 3,
                            DayID = 4,
                            TimeEnd = new TimeOnly(10, 0, 0),
                            TimeStart = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            SessionId = 24,
                            ClassId = 3,
                            DayID = 4,
                            TimeEnd = new TimeOnly(12, 0, 0),
                            TimeStart = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            SessionId = 25,
                            ClassId = 4,
                            DayID = 4,
                            TimeEnd = new TimeOnly(14, 30, 0),
                            TimeStart = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            SessionId = 26,
                            ClassId = 9,
                            DayID = 4,
                            TimeEnd = new TimeOnly(17, 0, 0),
                            TimeStart = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            SessionId = 27,
                            ClassId = 1,
                            DayID = 4,
                            TimeEnd = new TimeOnly(19, 0, 0),
                            TimeStart = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            SessionId = 28,
                            ClassId = 6,
                            DayID = 4,
                            TimeEnd = new TimeOnly(21, 0, 0),
                            TimeStart = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            SessionId = 29,
                            ClassId = 2,
                            DayID = 5,
                            TimeEnd = new TimeOnly(7, 30, 0),
                            TimeStart = new TimeOnly(6, 30, 0)
                        },
                        new
                        {
                            SessionId = 30,
                            ClassId = 1,
                            DayID = 5,
                            TimeEnd = new TimeOnly(10, 0, 0),
                            TimeStart = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            SessionId = 31,
                            ClassId = 3,
                            DayID = 5,
                            TimeEnd = new TimeOnly(12, 0, 0),
                            TimeStart = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            SessionId = 32,
                            ClassId = 4,
                            DayID = 5,
                            TimeEnd = new TimeOnly(14, 30, 0),
                            TimeStart = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            SessionId = 33,
                            ClassId = 8,
                            DayID = 5,
                            TimeEnd = new TimeOnly(17, 0, 0),
                            TimeStart = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            SessionId = 34,
                            ClassId = 2,
                            DayID = 5,
                            TimeEnd = new TimeOnly(19, 0, 0),
                            TimeStart = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            SessionId = 35,
                            ClassId = 3,
                            DayID = 5,
                            TimeEnd = new TimeOnly(21, 0, 0),
                            TimeStart = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            SessionId = 36,
                            ClassId = 11,
                            DayID = 6,
                            TimeEnd = new TimeOnly(7, 30, 0),
                            TimeStart = new TimeOnly(6, 30, 0)
                        },
                        new
                        {
                            SessionId = 37,
                            ClassId = 3,
                            DayID = 6,
                            TimeEnd = new TimeOnly(10, 0, 0),
                            TimeStart = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            SessionId = 38,
                            ClassId = 7,
                            DayID = 6,
                            TimeEnd = new TimeOnly(12, 0, 0),
                            TimeStart = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            SessionId = 39,
                            ClassId = 6,
                            DayID = 6,
                            TimeEnd = new TimeOnly(14, 30, 0),
                            TimeStart = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            SessionId = 40,
                            ClassId = 2,
                            DayID = 6,
                            TimeEnd = new TimeOnly(17, 0, 0),
                            TimeStart = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            SessionId = 41,
                            ClassId = 11,
                            DayID = 6,
                            TimeEnd = new TimeOnly(19, 0, 0),
                            TimeStart = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            SessionId = 42,
                            ClassId = 11,
                            DayID = 6,
                            TimeEnd = new TimeOnly(21, 0, 0),
                            TimeStart = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            SessionId = 43,
                            ClassId = 11,
                            DayID = 7,
                            TimeEnd = new TimeOnly(7, 30, 0),
                            TimeStart = new TimeOnly(6, 30, 0)
                        },
                        new
                        {
                            SessionId = 44,
                            ClassId = 3,
                            DayID = 7,
                            TimeEnd = new TimeOnly(10, 0, 0),
                            TimeStart = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            SessionId = 45,
                            ClassId = 6,
                            DayID = 7,
                            TimeEnd = new TimeOnly(12, 0, 0),
                            TimeStart = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            SessionId = 46,
                            ClassId = 7,
                            DayID = 7,
                            TimeEnd = new TimeOnly(14, 30, 0),
                            TimeStart = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            SessionId = 47,
                            ClassId = 1,
                            DayID = 7,
                            TimeEnd = new TimeOnly(17, 0, 0),
                            TimeStart = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            SessionId = 48,
                            ClassId = 11,
                            DayID = 7,
                            TimeEnd = new TimeOnly(19, 0, 0),
                            TimeStart = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            SessionId = 49,
                            ClassId = 11,
                            DayID = 7,
                            TimeEnd = new TimeOnly(21, 0, 0),
                            TimeStart = new TimeOnly(19, 0, 0)
                        });
                });

            modelBuilder.Entity("DobuMartial_project.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("MembershipId")
                        .HasColumnType("int");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DobuMartial_project.Models.UserSession", b =>
                {
                    b.Property<int>("SessionsSessionId")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SessionsSessionId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("UserSession");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DobuMartial_project.Models.Class", b =>
                {
                    b.HasOne("DobuMartial_project.Models.User", null)
                        .WithMany("ChosenMartialArts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("DobuMartial_project.Models.Session", b =>
                {
                    b.HasOne("DobuMartial_project.Models.Class", "Class")
                        .WithMany("Sessions")
                        .HasForeignKey("ClassId");

                    b.HasOne("DobuMartial_project.Models.Day", "Day")
                        .WithMany("Sessions")
                        .HasForeignKey("DayID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("DobuMartial_project.Models.User", b =>
                {
                    b.HasOne("DobuMartial_project.Models.Membership", "Membership")
                        .WithMany()
                        .HasForeignKey("MembershipId");

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("DobuMartial_project.Models.UserSession", b =>
                {
                    b.HasOne("DobuMartial_project.Models.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionsSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DobuMartial_project.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DobuMartial_project.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DobuMartial_project.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DobuMartial_project.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DobuMartial_project.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DobuMartial_project.Models.Class", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DobuMartial_project.Models.Day", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("DobuMartial_project.Models.User", b =>
                {
                    b.Navigation("ChosenMartialArts");
                });
#pragma warning restore 612, 618
        }
    }
}
